[package]
name = "async-graphql"
version = "1.9.17"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"
description = "The GraphQL server library implemented by rust"
publish = true
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/async-graphql/"
homepage = "https://github.com/sunli829/async-graphql"
repository = "https://github.com/sunli829/async-graphql"
keywords = ["futures", "async", "graphql"]
categories = ["network-programming", "asynchronous"]
readme = "README.md"

[features]
default = ["bson", "uuid", "url", "chrono-tz"]

[dependencies]
async-graphql-derive = { path = "async-graphql-derive", version = "1.9.17" }
graphql-parser = "=0.2.3"
anyhow = "1.0.26"
thiserror = "1.0.11"
async-trait = "0.1.24"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.48"
bytes = "0.5.4"
Inflector = "0.11.4"
base64 = "0.12.0"
byteorder = "1.3.4"
futures = "0.3.0"
parking_lot = "0.10.0"
chrono = "0.4.10"
slab = "0.4.2"
once_cell = "1.3.1"
itertools = "0.9.0"
tempdir = "0.3.7"
httparse = "1.3.4"
mime = "0.3.16"
http = "0.2.1"
fnv = "1.0.6"
regex = "1.3.5"
async-stream = "0.2.1"
bson = { version = "0.14.1", optional = true }
uuid = { version = "0.8.1", optional = true }
url = { version = "2.1.1", optional = true }
chrono-tz = { version = "0.5.1", optional = true }

[dev-dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
serde = "1.0.104"
serde_derive = "1.0.104"

[workspace]
members = [
    "async-graphql-derive",
    "async-graphql-actix-web",
    "async-graphql-warp",
]